spring:
  database:
    sql:
      enabled: false
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/dbtechchallange?authSource=admin
      database: dbtechchallange
  datasource:
    url: jdbc:mysql://localhost:3306/dbtechchallange?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: turmafiap
    password: Tech@Challange#
  custom:
    db-type: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: http://localhost:4566
        region: us-east-1