spring:
  data:
    mongodb: 
      uri: ${MONGODB_URI}
      database: dbtechchallenge

cloud:
  aws:
    region:
      static: us-east-1
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
      session-token: ${AWS_SESSION_TOKEN}
    sqs:
      main-queue:
        name: payment-order-main
        url: ${SQS_MAIN_QUEUE_URL}
      dlq:
        name: payment-order-dlq
        url: ${SQS_DLQ_URL}