spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbtechchallange?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: turmafiap
    password: Tech@Challange#
  custom:
    db-type: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  h2:
    console:
      enabled: true
      path: /h2-console

