apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-management
  template:
    metadata:
      labels:
        app: order-management
    spec:
      hostAliases:
      - ip: "52.87.82.147"
        hostnames:
        - "tech-challenge-cluster.bwktl.mongodb.net"
      dnsConfig:
        options:
          - name: timeout
            value: "30"
          - name: attempts
            value: "5"
      containers:
      - name: order-management
        image: order-management:local
        imagePullPolicy: Never
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "local-private"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: order-management-secrets
              key: MONGODB_URI
        - name: AWS_REGION
          value: "us-west-2"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: order-management-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: order-management-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: order-management-secrets
              key: AWS_SESSION_TOKEN
        ports:
        - containerPort: 8080
