name: Destroy Infrastructure

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_DEFAULT_REGION: us-east-1
  TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
  MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
  MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
  MONGODB_ATLAS_ORG_ID: ${{ secrets.MONGODB_ATLAS_ORG_ID }}
  MONGODB_ATLAS_PUBLIC_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
  MONGODB_ATLAS_PRIVATE_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}
  LOCAL_IP: "${{ secrets.LOCAL_IP }}"
  

jobs:
  destroy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terraform
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update && sudo apt-get install terraform

      - name: Create tfvars file
        working-directory: ./infrastructure/terraform
        run: |
          cat > terraform.tfvars << EOF
          mongodb_username         = "${{ env.MONGODB_USERNAME }}"
          mongodb_password         = "${{ env.MONGODB_PASSWORD }}"
          mongodb_atlas_org_id     = "${{ env.MONGODB_ATLAS_ORG_ID }}"
          mongodb_atlas_public_key  = "${{ env.MONGODB_ATLAS_PUBLIC_KEY }}"
          mongodb_atlas_private_key = "${{ env.MONGODB_ATLAS_PRIVATE_KEY }}"
          local_ip                 = "${{ env.LOCAL_IP }}"
          EOF

      - name: Initialize Terraform
        working-directory: ./infrastructure/terraform
        run: terraform init -backend-config="bucket=${TF_STATE_BUCKET}" -backend-config="key=mongodb.tfstate" -backend-config="region=us-east-1"

      - name: Destroy MongoDB Atlas Infrastructure
        working-directory: ./infrastructure/terraform
        run: terraform destroy -auto-approve